#!/bin/bash
# ====================================================
#   BHARAT ALGOVERSE v3.0 - DUAL-ISLAND SETUP
# ====================================================
# This script sets up TWO isolated environments on the VPS:
# 1. BHARAT-BUYING (Port 8501)
# 2. BHARAT-SELLING (Port 8502)

REPO_URL="https://github.com/gurjeetsinghgill8-web/BHARAT-ALGO-TRADING-APP.git"

echo "💉 Starting Surgical Separation of Engines..."
sudo pkill -9 python3 2>/dev/null || true
sudo pkill -9 streamlit 2>/dev/null || true
rm -f /root/BHARAT-BUYING/bot.lock /root/BHARAT-SELLING/bot.lock /root/BHARAT-ALGO-TRADING-APP/bot.lock
sudo apt-get update -q && sudo apt-get install -y -q python3-venv

setup_instance() {
    FOLDER=$1
    PORT=$2
    MODE=$3
    DB=$4
    PREFIX=$5
    TF=$6

    echo "----------------------------------------------------"
    echo "🏗️ Setting up $MODE Island in $FOLDER..."
    echo "----------------------------------------------------"

    # Create folder and clone if not exists
    if [ ! -d "$FOLDER" ]; then
        git clone $REPO_URL $FOLDER
    fi

    cd $FOLDER
    git fetch --all
    git reset --hard origin/main
    git pull origin main

    # 1. Create Virtual Environment if not exists
    if [ ! -d "venv" ]; then
        python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -q --upgrade pip
    pip install -q requests pandas  # Ensure core libs are first
    pip install -q -r requirements.txt

    # 2. Create Surgical config.py for this instance
    cat > config.py << EOF
# AUTO-GENERATED BY SURGICAL DEPLOYMENT
STRATEGY_MODE = "$MODE"
TIMEFRAME = "$TF"
STABLE_CANDLE_ONLY = True
NIFTY_LOT_SIZE = 65
DB_NAME = "$DB"
PORT = $PORT
TELEGRAM_PREFIX = "$PREFIX"
LOG_FILE = "${MODE,,}_trades.log"
EOF

    # 3. Create systemd service for Engine
    SERVICE_NAME="bharat_${MODE,,}_engine"
    cat > /etc/systemd/system/${SERVICE_NAME}.service << EOF
[Unit]
Description=Bharat AlgoVerse $MODE Engine
After=network.target

[Service]
User=root
WorkingDirectory=$FOLDER
ExecStart=$FOLDER/venv/bin/python3 main.py
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
EOF

    # 4. Create systemd service for Dashboard
    DASH_NAME="bharat_${MODE,,}_dash"
    cat > /etc/systemd/system/${DASH_NAME}.service << EOF
[Unit]
Description=Bharat AlgoVerse $MODE Dashboard
After=network.target

[Service]
User=root
WorkingDirectory=$FOLDER
ExecStart=$FOLDER/venv/bin/python3 -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    # 5. Enable and Restart
    systemctl daemon-reload
    systemctl enable $SERVICE_NAME $DASH_NAME
    systemctl restart $SERVICE_NAME $DASH_NAME
    
    echo "✅ $MODE Island is LIVE on Port $PORT"
}

# --- SURGERY EXECUTION ---

# Island 1: BUYING (Port 8501)
setup_instance "/root/BHARAT-BUYING" 8501 "BUYING" "buying.db" "🟢 [BUYING BOT]" "5m"

# Island 2: SELLING (Port 8502)
setup_instance "/root/BHARAT-SELLING" 8502 "SELLING" "selling.db" "🔴 [SELLING BOT]" "15m"

# Firewall
sudo ufw allow 8501/tcp
sudo ufw allow 8502/tcp

echo ""
echo "===================================================="
echo "  SURGERY COMPLETE! Both Islands are Isolated."
echo ""
echo "  Buying Dashboard : http://46.224.133.16:8501"
echo "  Selling Dashboard: http://46.224.133.16:8502"
echo "===================================================="
