# --- BHARAT ALGOVERSE v3.0 | STABLE V3 CONFIGURATION ---
# RESTORED MASTER VERSION: Pure Option Buying | 5-Minute | 6 Lots

STRATEGY_MODE = "BUYING"
TIMEFRAME = "5m"
STABLE_CANDLE_ONLY = True 

# MASTER LOT SETTINGS (Dr. Saab's Strict Rule)
CRYPTO_LOT_SIZE = 6

# DATABASE & UI
DB_NAME = "buying.db"
PORT = 8501
TELEGRAM_PREFIX = "🚀 [BHARAT V3 STABLE]"

# LOGGING
LOG_FILE = "buying_trades.log"
